name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker compose build

  cd:
    name: Continuous Deployment
    runs-on: self-hosted
    needs: ci

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Update source code
        run: |
          cd ~/vatlieu
          git pull origin main

      - name: Deploy application
        run: |
          cd ~/vatlieu
          docker compose up -d --build

      - name: Verify running containers
        run: docker ps